bind 0.0.0.0
protected-mode no
port 6379
dir /data
save ""
appendonly yes
appendfsync always
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-rewrite-incremental-fsync yes
maxmemory 2gb
maxmemory-policy noeviction
io-threads 3
